### ISSUE TITLE
Bug: 3.38+ does not detect iOS Safari features properly

### ISSUE THREAD

**Issue by infabo** [polyfillpolyfill/polyfill-service#2421]
Bug report

## What

Until including 3.37 the fetch polyfill is not delivered, because safari 10+ has support for fetch api.
Starting with 3.38 the fetch-polyfill is delivered falsely.

## Details

iOS 12/13/14
Safari browser

Used URL: https://polyfill.io/v3/polyfill.min.js?features=default%2Cfetch

**Comment by aronwoost** [comment]
I'm also seeing the issue for `ResizeObserver`.

Open in current desktop Safari: https://polyfill.io/v3/polyfill.min.js?features=ResizeObserver (should be empty)

Also we see a lot of browser errors (`ResizeObserver`, `Object.keys`, `Intl`) in older Safari versions (both desktop and mobile). I think the Safari detection is not fully functional.

**Comment by aronwoost** [comment]
This is our TrackJS graph for `ResizeObserver` issue on older Safari browsers (desktop and mobile). `Can't find variable: ResizeObserver`

![image](https://user-images.githubusercontent.com/408962/95465746-cc691c00-097b-11eb-9ebf-684fbc948e65.png)

Mysterious I find, that the numbers go up slowly. Is this maybe an infrastructure issue? Some broken node that is delivering broken data?

**Comment by JakeChampion** [comment]
Hi @aronwoost and @infabo, could you both post the full user-agent strings of the browsers which are not working correctly please? This will help us identify what the issue is 👍

**Comment by aronwoost** [comment]
Current desktop safari, where `ResizeObserver` is falsely delivered: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15` (also see link above 👆)

Mobile safari, where `ResizeObserver` is falsely **not** delivered: `Mozilla/5.0 (iPhone; CPU iPhone OS 12_4_8 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1`

**Comment by aronwoost** [comment]
How to reproduce the `ResizeObserver` issue: #2428

**Comment by aronwoost** [comment]
Is this fixed with #2428 (for me it is, not sure about `fetch`)?

**Comment by JakeChampion** [comment]
This is still an issue, it is an issue in our user-agent detection codebase --> https://github.com/Financial-Times/polyfill-useragent-normaliser/issues/96
